apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: nginx-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-init
  template:
    metadata:
      labels:
        app: nginx-init
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      initContainers:
      - name: service-check
        image: busybox
        command: [ 'sh', '-c', "until nslookup deploy2-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for deploy2-svc; sleep 2; done" ]
