apiVersion: v1
kind: Pod
metadata:
  name: multitool-pod
  labels:
    app: nginx-multitool
spec:
  containers:
  - name: multitool-pod
    image: wbitt/network-multitool
    ports:
    - containerPort: 8080
